### ISSUE TITLE
is this  var signal = 'SIGKILL';  variable being used

### ISSUE THREAD

**Issue by benjaminlees** [dwyl/terminate#16]
@nelsonic were you planning on passing the signal variable as the first argument to child_process.spawn method ?

**Comment by nelsonic** [comment]
Good question @benjaminlees 
the `signal` was meant to be passe into `child_process.spawn` but for some reason is not being passed.
https://github.com/dwyl/terminate/blob/3421c3a13b7caace49396dd65acca914e92a6d8f/terminate.js#L21

We can either remove line 19 or pass in the `SIGKILL` instead of `kill` ... what is your preference?

**Comment by benjaminlees** [comment]
@nelsonic  i think removing line 19 would best as using kill will child_process.spawn is clear and is also the way that psTree suggests. Do you want me to make a pr

**Comment by nelsonic** [comment]
Yeah, go for it. :+1: 
But please merge: https://github.com/dwyl/terminate/pull/15 first 
so you are working with the latest `devDependencies` :+1:

**Comment by benjaminlees** [comment]
ok

**Comment by benjaminlees** [comment]
@nelsonic I do not have the ability to merge prs

**Comment by nelsonic** [comment]
@benjaminlees ah... please enable 2-factor Auth to unlock `Admin` level in dwyl ...
![benjaminlees-no-2-factor-auth](https://cloud.githubusercontent.com/assets/194400/12767779/3969f954-ca03-11e5-9e45-b9fb2b029b6d.png)
see: https://help.github.com/articles/about-two-factor-authentication/ :wink:

**Comment by benjaminlees** [comment]
@nelsonic I am now able thanks

**Comment by nelsonic** [comment]
Fixed by PR: #18
