### ISSUE TITLE
Update documentation in readme to reflect optional parameters terminate function accepts.

### ISSUE THREAD

**Issue by nelsonic** [dwyl/terminate#30]
In @jedwards1211's Pull Request https://github.com/dwyl/terminate/pull/27 all parameters to `terminate` beyond the process ID `pid` were made _optional_ ... 👍 
This has not been reflected in the readme... 😞 

Ideally what we would like to have here is something similar to: https://github.com/dwyl/hapi-auth-jwt2#documentation where each required/optional parameter is explained.

**Comment by micalevisk** [comment]
I guess the type defs should be changed as well

https://github.com/dwyl/terminate/blob/5e79c42a3fc04b41fac9a346d646da21f599c2c9/index.d.ts#L2

the above doesn't cover the below

https://github.com/dwyl/terminate/blob/5e79c42a3fc04b41fac9a346d646da21f599c2c9/terminate.js#L6-L23

in fact, those typings are not used because `index.d.ts` is not listed on `package.json` (just need to add the entry `"types": "index.d.ts"` to fix that)

**Comment by nelsonic** [comment]
@micalevisk good catch. Thanks for creating the PR! 👍

**Comment by micalevisk** [comment]
do you still think that having those descriptions on the README as well is worth it? If yes, I will open a PR adding them. Otherwise we can close this :smiley:
